### PR TITLE
fix: footer text aligned in center

### PR DESCRIPTION
**Pull request by HeetVekariya**
# Fixes Issue
- ### Issue: #5 
- ### **Footer text is not aligned according to website flow**

---
# Solution
- ### Change the CSS to ```text-align: center;```   for the parent tag of the ```<span>``` tag which contains the footer text

---
# ✔️ Check List
## -  The title and description of the PR is clear and explains the approach.

---
# Screenshort
image

### CODE REVIEW

**Comment by intrepidbird** [comment]
Very cool!

Why is it a pull request though?

**Comment by HeetVekariya** [comment]
If i don;t do through then it won't be counted under Hacktoberfest

**Comment by intrepidbird** [comment]
Oh I see

**Comment by intrepidbird** [comment]
wait i will reopen just in case

**Comment by HeetVekariya** [comment]
Okay

**Comment by intrepidbird** [comment]
Sure, please do make the website on Github

**Pull request merged**
